### ISSUE TITLE
Support for UTC moment objects

### ISSUE THREAD

**Issue by Stansbridge** [CalebMorris/react-moment-proptypes#20]
I'm looking for a way to restrict the moment object to a UTC configured moment object.

If this is something you'd accept for your API i'd love to request the feature or offer a pull request... let me know your thoughts. 

I am always happy to fork if you are not fond of the suggestion, Thanks!

**Comment by CalebMorris** [comment]
The main purpose of propTypes, as far as I have seen, is type check in development with them being stripped from a production release. I can see a couple use-cases where that would be useful and I'd want to have more specific attribute checks.  

Since Moment provides a `isUTC` function to check this it seems fairly straight forward to apply this to any Moment object passed and chained to a evaluated on that is passed by string. I'd also want to allow any other checks against the method. In order to implement this I'd want to try out a couple different approaches to see what seems simple enough.

Such as
```
  propTypes : {
    dateThing : momentPropTypes.momentObj.withAttributes(function(momentObj) {
      return momentObj.isUTC();
    }),
  },
```
or something similar.

What do you think? Did you have a different look of how you would implement this? I'm always open for a pull-request if you have something in mind and are willing to do the implementation and testing.

**Comment by Stansbridge** [comment]
I think we're on the same page with making it simple :-).

I had a small thought about applying some sort of code generation to mill out a few permutations of attributes, I fear this would get out of hand quickly.

Your proposed API seems like a good middleground, we could always wrap this in a file our end if it's causing us code duplication issues.

We're more than happy to make a pull request and test to your requirements, have a think and let me know what would be best for your repo.

Anthony

**Comment by CalebMorris** [comment]
Added new API `.withPredicate(func)` and `.withPredicate(func).isRequired` starting with v1.3.0.
Thanks for the request and let me know if you want to add anything else or there is something wrong with the implementation.

**Comment by Stansbridge** [comment]
@CalebMorris Thank you very much, looks great.
