### ISSUE TITLE
DurationString support

### ISSUE THREAD

**Issue by alex-shamshurin** [CalebMorris/react-moment-proptypes#29]

**Comment by CalebMorris** [comment]
Currently validates that duration is in Object form [index.js#L119](https://github.com/CalebMorris/react-moment-proptypes/blob/master/src/index.js#L119), but Moment allows a string format that moment converts.
I'm assuming that this is what you are referring to and requesting.

Sounds good to me and I'll add it once I get a chance and can finish some of the testing changes I've been working on

**Comment by CalebMorris** [comment]
For context the Duration documentation can be found at [http://momentjs.com/docs/#/durations/](http://momentjs.com/docs/#/durations/).

Considering the variety of support levels of what is considered a valid Duration string (and even detecting if a Duration object is valid), I'm not sure it is simple to maintain support direct string input.

@alex-shamshurin Can you describe a specific use-case that it would be more beneficial to wrap strings rather than directly passing a Duration object?
